export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ITEM_SET_SUCCESS = 'ITEM_SET_SUCCESS';
export const ITEM_SET_FAIL = 'ITEM_SET_FAIL';
export const ITEM_SET_START = 'ITEM_SET_START';

export const SHOW_MODEL = 'SHOW_MODEL';

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";

export const EMPTY_ERROR = "EMPTY_ERROR";

export const ISLOADING_TRUE = "ISLOADING_TRUE";

export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const ADDITEM_TO_USER_SUCCESS = "ADDITEM_TO_USER_SUCCESS";
export const ADDITEM_TO_USER_ERROR = "ADDITEM_TO_USER_ERROR";